import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const pretnedard = localFont({
  src: "../lib/PretendardVariable.woff2",
  display: "swap",
  weight: "400 700",
  variable: "--font-pretendard",
});

const suit = localFont({
  src: "../lib/SUIT-Variable.woff2",
  display: "swap",
  weight: "400 700",
  variable: "--font-suit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={suit.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
