# frontend/nginx/nginx.conf

upstream nextjs {
    server localhost:3000;
}

server {
    listen 80;
    server_name suitdio.com www.suitdio.com;

    location / {
        proxy_pass http://nextjs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Cookie $http_cookie;
        proxy_cookie_domain mileque.com .mileque.com;
        proxy_set_header X-CSRFToken $http_x_csrf_token;
    }

    location /v1/ {
        proxy_pass https://backend.suitdio.com;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header X-CSRFToken $http_x_csrf_token;
        proxy_cookie_domain mileque.com .mileque.com;
    }

    # Error page handling
    error_page 502 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}