name: Deploy to Develop EC2

on:
  push:
    branches:
      - "develop"      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout latest version
      - name: Checkout source code
        uses: actions/checkout@v4.1.1

      # 2. Cache node_modules for faster dependency installation
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      # 3. Setup environment variables
      - name: Set environment variables
        run: |
          echo "NEXT_PUBLIC_POST_API_URL=$NEXT_PUBLIC_POST_API_URL" >> .env
          echo "NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID" >> .env
        env:
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}

      # 4. Build and push Docker image
      - name: Build and push Docker image
        run: |
          set -e  # Stop script on any error
          docker login -u $DOCKER_ID -p $DOCKER_TOKEN
          docker build -t $DOCKER_ID/$DOCKER_REPO:frontdev ./
          docker push $DOCKER_ID/$DOCKER_REPO:frontdev
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 5. SSH into EC2 and deploy the new Docker container
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-37-138-4.ap-northeast-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Stop script on any error
            sudo docker login -u $DOCKER_ID -p $DOCKER_TOKEN
            sudo docker stop front || true
            sudo docker rm front || true
            sudo docker pull $DOCKER_ID/$DOCKER_REPO:frontdev
            sudo docker network ls | grep mileque-network || docker network create mileque-network
            sudo docker run -d --name front --network mileque-network -p 3000:3000 $DOCKER_ID/$DOCKER_REPO:frontdev
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  notify-success:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification on Success
        if: success()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "blocks": [
                { "type": "divider" },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: *Build and Deploy Success*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    { "type": "mrkdwn", "text": "*Repository*\n${{ github.repository }}" },
                    { "type": "mrkdwn", "text": "*Branch*\n${{ github.ref }}" },
                    { "type": "mrkdwn", "text": "*Commit*\n${{ github.sha }}" },
                    { "type": "mrkdwn", "text": "*Author*\n${{ github.actor }}" },
                    { "type": "mrkdwn", "text": "*Event Name*\n${{ github.event_name }}" },
                    { "type": "mrkdwn", "text": "*Workflow*\n${{ github.workflow }}" },
                    { "type": "mrkdwn", "text": "*Job ID*\n${{ github.run_id }}" },
                    { "type": "mrkdwn", "text": "*Duration*\n${{ github.run_duration_ms }} ms" }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    { "type": "button", "text": { "type": "plain_text", "text": "View Action" }, "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FRONT_SLACK_WEBHOOK_URL }}

  notify-failure:
    runs-on: ubuntu-latest
    if: failure()  
    steps:
      - name: Slack Notification on Failure
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "blocks": [
                { "type": "divider" },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":x: *Build or Deploy Failure*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    { "type": "mrkdwn", "text": "*Repository*\n${{ github.repository }}" },
                    { "type": "mrkdwn", "text": "*Branch*\n${{ github.ref }}" },
                    { "type": "mrkdwn", "text": "*Commit*\n${{ github.sha }}" },
                    { "type": "mrkdwn", "text": "*Author*\n${{ github.actor }}" },
                    { "type": "mrkdwn", "text": "*Event Name*\n${{ github.event_name }}" },
                    { "type": "mrkdwn", "text": "*Workflow*\n${{ github.workflow }}" },
                    { "type": "mrkdwn", "text": "*Job ID*\n${{ github.run_id }}" },
                    { "type": "mrkdwn", "text": "*Duration*\n${{ github.run_duration_ms }} ms" }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    { "type": "button", "text": { "type": "plain_text", "text": "View Action" }, "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FRONT_SLACK_WEBHOOK_URL }}
