name: Deploy to Develop EC2

on:
  push:
    branches:
      - "develop"      
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-37-138-4.ap-northeast-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd milque-front
            git reset --hard HEAD
            git pull origin develop
            if [ ! -f .env ]; then
              echo "${{ secrets.ENV }}" > .env
            else
              echo "${{ secrets.ENV }}" > .env.tmp
              mv .env.tmp .env
            fi
            sudo docker system prune -a -f --volumes
            sudo docker build -t mileque-front:dev .
            sudo docker stop front || true
            sudo docker rm front || true
            sudo docker network ls | grep mileque-network || docker network create mileque-network
            sudo docker run -d --name front --network mileque-network -p 3000:3000 mileque-front:dev
            
      - name: Slack Notification on Success
        if: success()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "blocks": [
                { "type": "divider" },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: *Build Test Success*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*\n${{ github.ref }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*\n${{ github.sha }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event Name*\n${{ github.event_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow*\n${{ github.workflow }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job ID*\n${{ github.run_id }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Duration*\n${{ github.run_duration_ms }} ms"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Action"
                      },
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FRONT_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      
      - name: Slack Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "blocks": [
                { "type": "divider" },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":x: *Build Test Failure*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*\n${{ github.ref }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*\n${{ github.sha }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event Name*\n${{ github.event_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow*\n${{ github.workflow }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job ID*\n${{ github.run_id }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Duration*\n${{ github.run_duration_ms }} ms"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Action"
                      },
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FRONT_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
