name: Build Test Develop Branch

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"
    paths:
      - 'feat/**'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Cache Next.js build cache
        id: cache-nextjs
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-cache-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Extract branch name
        id: extract_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: 211125602993.dkr.ecr.ap-northeast-2.amazonaws.com/mileque-front #:${{ env.branch_name }}
          # build-args: |
          #   NEXT_PUBLIC_URI=${{ secrets.NEXT_PUBLIC_URI }}

      - name: Post job cleanup
        run: |
          echo "Cleaning up caches"
          rm -rf .next/cache
          rm -rf **/node_modules
          
      - name: Slack Notification on Success
        if: success() # 이 step은 job이 성공한 경우에만 실행된다.
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "channel": "front-request",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "Build Test Success :white_check_mark:",
                  "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                  "text": "The action has succeeded for the following job: `${{ github.job }}`",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FRONT_SLACK_WEBHOOK_URL }}
      
      - name: Slack Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "channel": "front-request",
              "attachments": [
                {
                  "color": "#ff0000",
                  "title": "Build Test Failure :x:",
                  "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                  "text": "The action has failed for the following job: `${{ github.job }}`",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref }}",
                      "short": true
                    }
                  ]      
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FRONT_SLACK_WEBHOOK_URL }}
